version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
        - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flink-topic-in:1:1,flink-topic-out:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
